# Generated by Django 5.0.3 on 2024-04-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор отзыва')),
                ('platform', models.CharField(choices=[('ЛучшийОбмен', 'ЛучшийОбмен')], max_length=50, verbose_name='Платформа')),
                ('content', models.TextField(verbose_name='Текст отзыва')),
                ('date_posted', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
