# Generated by Django 5.0.3 on 2024-04-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('EN', 'на английском'), ('RU', 'На русском')], default='EN', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('EN', 'на английском'), ('RU', 'На русском')], default='EN', max_length=2),
        ),
    ]
