# Generated by Django 5.0.3 on 2024-04-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_language_alter_userprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
    ]
