# Generated by Django 5.0.3 on 2024-04-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_language_remove_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
