# Generated by Django 5.0.3 on 2024-04-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('direction', models.CharField(max_length=100, verbose_name='Направление')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen')], max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заявка валюты',
                'verbose_name_plural': 'Заявки валюты',
            },
        ),
    ]
