# Generated by Django 5.0.3 on 2024-04-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('image', models.ImageField(blank=True, null=True, upload_to='currency_news/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость о валюте',
                'verbose_name_plural': 'Новости о валютах',
            },
        ),
    ]
