# Generated by Django 5.0.3 on 2024-04-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fag', '0003_faq_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian')], default='ru', max_length=2, verbose_name='Язык'),
        ),
    ]
