# Generated by Django 5.0.3 on 2024-04-29 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fag', '0004_alter_faq_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='language',
        ),
    ]
