# Generated by Django 5.0.3 on 2024-04-24 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCAMLCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_status', models.BooleanField(default=False, verbose_name='Статус KYC-проверки')),
                ('aml_status', models.BooleanField(default=False, verbose_name='Статус AML-проверки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения KYC')),
                ('aml_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения AML')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'KYC/AML Проверка',
                'verbose_name_plural': 'KYC/AML Проверки',
                'ordering': ['-created_at'],
            },
        ),
    ]
