# Generated by Django 5.0.3 on 2024-04-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycaml', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kycamlcheck',
            options={'verbose_name': 'KYC/AML Запись', 'verbose_name_plural': 'KYC/AML Записи'},
        ),
        migrations.RemoveField(
            model_name='kycamlcheck',
            name='aml_status',
        ),
        migrations.RemoveField(
            model_name='kycamlcheck',
            name='aml_verified_at',
        ),
        migrations.RemoveField(
            model_name='kycamlcheck',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kycamlcheck',
            name='kyc_status',
        ),
        migrations.RemoveField(
            model_name='kycamlcheck',
            name='kyc_verified_at',
        ),
        migrations.RemoveField(
            model_name='kycamlcheck',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='kycamlcheck',
            name='user',
        ),
        migrations.AddField(
            model_name='kycamlcheck',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycamlcheck',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
